name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: py${{ matrix.python-version }} / ${{ matrix.os }} / PyYAML~=${{ matrix.pyyaml-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9"]
        pyyaml-version: ["3.13", "4.2b4", "5.4", "6.0"]
        include:
          - { os: ubuntu-latest, python-version: "3.13", pyyaml-version: "6.0" }
          - { os: macos-latest, python-version: "3.13", pyyaml-version: "6.0" }
          - { os: windows-latest, python-version: "3.13", pyyaml-version: "6.0" }

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install
        run: python -m pip install -q pytest pytest-cov pyyaml~=${{ matrix.pyyaml-version }} -e .
      - name: Run tests py${{ matrix.python-version }} / ${{ matrix.os }} / PyYAML~=${{ matrix.pyyaml-version }}
        run: python -m pytest --cov-branch --cov=oyaml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  tests-27:
    name: Python 2.7 on ubuntu-20.04
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        pyyaml-version: ["3.13", "4.2b4", "5.4"]

    container:
      image: python:2.7-buster

    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: python -m pip install -q pytest pytest-cov pyyaml~=${{ matrix.pyyaml-version }} -e .
      - name: Run tests py${{ matrix.python-version }} / ${{ matrix.os }} / PyYAML~=${{ matrix.pyyaml-version }}
        run: python -m pytest --cov-branch --cov=oyaml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
